import {test} from 'node:test';import assert from 'node:assert/strict';import {createContext,runInContext} from 'node:vm';import {readFileSync} from 'node:fs';
const cases=[['fitness-log','/metrics','POST'],['fitness-edit','/metrics/record','PUT'],['rhythm-plan','/planner','POST'],['rhythm-plan-edit','/planner/record','PUT'],['rhythm-plan-eaten','/planner/record/log','POST'],['rhythm-repeat','/nutrition/repeat','POST']];
function fixture(kind:string){let release:any,fail:any;const writes:any[]=[],listeners=new Map<string,any[]>(),moves:string[]=[],toasts:string[]=[];let renders=0;const attrs=new Map([['data-form',kind]]),control={type:'number',tagName:'INPUT',readOnly:false,value:'3'},form={isConnected:true,elements:[control],innerHTML:'entered data',setAttribute:(k:string,v:string)=>attrs.set(k,v),removeAttribute:(k:string)=>attrs.delete(k)};
 const c=createContext({document:{addEventListener(name:string,fn:any){listeners.set(name,[...(listeners.get(name)||[]),fn]);}},window:{},location:{hash:kind.startsWith('fitness')?'#/portal/progress?metric=energy':'#/portal/planner?day=2026-10-01'},session:{user:{id:'one'}},renderVersion:1,form,URLSearchParams,esc:(s:string)=>s,route:()=>'/portal/progress',toast:(s:string)=>toasts.push(s),navigate:(p:string)=>moves.push(p),render:async()=>{renders++;},api:(...args:any[])=>{writes.push(args);return new Promise((yes,no)=>{release=yes;fail=no;});}});
 for(const file of ['save-workflow.js','fitness.js','rhythm.js'])runInContext(readFileSync(new URL('../public/'+file,import.meta.url),'utf8'),c);
 const run=()=>runInContext(`${kind.startsWith('fitness')?'submitFitnessForm':'submitRhythmForm'}(${JSON.stringify(kind)},{id:'record',day:'2026-10-01',quantity:'2',value:'3',version:'4',reps:'5',unit:'kg',metric:'strength_load',context:'squat',idempotency_key:'stable'},form)`,c);
 return {c,form,control,attrs,writes,moves,toasts,listeners,run,finish:()=>release({ok:true}),fail:()=>fail(Error('network outcome unknown')),get renders(){return renders;}};
}
for(const [kind,path,method] of cases)test(`${kind} writes captured payload once and cannot replace a newer view`,async()=>{const h=fixture(kind),pending=h.run();assert.equal(h.writes[0][0],path);assert.equal(h.writes[0][1],method);const payload=h.writes[0][2];if(kind.startsWith('fitness')){assert.equal(payload.value,3);assert.equal(payload.reps,5);assert.equal(payload.version,4);assert.equal(payload.context,'squat');assert.equal(payload.unit,'kg');}else assert.equal(payload.quantity,2);if(kind!=='rhythm-plan-eaten')assert.equal(payload.idempotency_key,'stable');assert.equal(h.control.readOnly,true);await h.run();assert.equal(h.writes.length,1);h.c.location.hash='#/portal/profile';h.c.renderVersion++;h.finish();await pending;assert.equal(h.renders,0);assert.deepEqual(h.moves,[]);assert.equal(h.form.innerHTML,'entered data');assert.equal(h.control.readOnly,false);});
for(const kind of ['fitness-edit','rhythm-plan-edit'])test(`${kind} failure retains input and retries with the same version`,async()=>{const h=fixture(kind),pending=h.run();h.fail();await assert.rejects(pending);assert.equal(h.attrs.get('data-form'),kind);assert.equal(h.control.value,'3');assert.equal(h.control.readOnly,false);const retry=h.run();assert.equal(h.writes[1][2].version,4);h.finish();await retry;assert.equal(h.renders,1);});
test('The shared lifecycle is loaded before its callers and served by the explicit static allowlist',()=>{const index=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');assert.ok(index.indexOf('/save-workflow.js')<index.indexOf('/nutrition.js'));for(const file of ['fitness.js','rhythm.js'])assert.ok(index.indexOf('/save-workflow.js')<index.indexOf('/'+file));assert.match(readFileSync(new URL('../src/server.ts',import.meta.url),'utf8'),/save-workflow\.js.*text\/javascript/);});

test('A cross-page planner save confirms in place and leaves navigation explicit',async()=>{const h=fixture('rhythm-plan');h.c.location.hash='#/portal/recipe?id=one';const pending=h.run();h.finish();await pending;assert.equal(h.renders,0);assert.deepEqual(h.moves,[]);assert.equal(h.attrs.has('data-form'),false);assert.match(h.form.innerHTML,/View saved planner/);assert.match(h.form.innerHTML,/#\/portal\/planner\?day=2026-10-01/);});
