CREATE TABLE exercises (
 id TEXT PRIMARY KEY, title TEXT NOT NULL, category TEXT NOT NULL,
 equipment TEXT NOT NULL DEFAULT '', instructions TEXT NOT NULL,
 video_url TEXT NOT NULL DEFAULT '', video_caption TEXT NOT NULL DEFAULT '',
 animation TEXT NOT NULL DEFAULT '' CHECK(animation IN ('','squat','wall-push','hinge','row')),
 is_demo INTEGER NOT NULL DEFAULT 0 CHECK(is_demo IN (0,1)),
 archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)),
 version INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE recipes ADD COLUMN is_demo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE templates ADD COLUMN is_demo INTEGER NOT NULL DEFAULT 0;
CREATE TABLE content_packs (id TEXT PRIMARY KEY, installed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
