import type { DatabaseSync } from 'node:sqlite';
import { transaction,id } from './db.ts';
export class ContactError extends Error { status:number; constructor(message:string,status=400){super(message);this.status=status;} }
const fail=(message:string):never=>{throw new ContactError(message);};
function input(value:unknown,name:string,max:number){if(typeof value!=='string'||value.length>max)fail(`${name} must be text, at most ${max} characters.`);return value.trim();}
function platformUrl(value:string,hosts:string[]){let url:URL;try{url=new URL(value);}catch{fail('Use a complete HTTPS profile link.');}if(url.protocol!=='https:'||!hosts.includes(url.hostname)||url.username||url.password||url.port||url.search||url.hash||value.includes('\\'))fail('Use a clean HTTPS link on the correct platform, without tracking parameters or extra paths.');return url;}
export function whatsappNumber(value:unknown){let s=input(value,'WhatsApp number',200);if(!s)return '';if(/^https?:/i.test(s)){const u=platformUrl(s,['wa.me']);if(!/^\/[1-9]\d{6,14}\/?$/.test(u.pathname))fail('Use a wa.me link containing only the international phone number.');s='+'+u.pathname.replaceAll('/','');}if(!/^\+[1-9][\d ()-]*$/.test(s))fail('Include + and the country code, for example +44, followed by the number without its domestic leading zero.');const digits=s.replace(/[ ()-]/g,'');if(!/^\+[1-9]\d{6,14}$/.test(digits))fail('Use 7–15 digits with the international country code.');return digits;}
export function instagramHandle(value:unknown){let s=input(value,'Instagram profile',200);if(!s)return '';if(/^https?:/i.test(s)){const u=platformUrl(s,['instagram.com','www.instagram.com']);if(!/^\/[^/]+\/?$/.test(u.pathname))fail('Use the Instagram profile link, not a post, reel or message link.');s=u.pathname.replaceAll('/','');}s=s.replace(/^@/,'').toLowerCase();if(!/^[a-z0-9_](?:[a-z0-9_.]{0,28}[a-z0-9_])?$/.test(s)||s.includes('..')||['p','reel','reels','stories','accounts','explore','direct','about','legal','developer','challenge'].includes(s))fail('Use a valid Instagram username or its profile link (up to 30 letters, digits, dots or underscores).');return s;}
export function contactSettings(db:DatabaseSync){return db.prepare('SELECT version,whatsapp_number,whatsapp_visibility,instagram_handle,instagram_visibility,response_note,updated_at FROM contact_settings WHERE id=1').get() as any;}
export function visibleContact(settings:any,signedIn=false){const show=(visibility:string)=>visibility==='public'||(signedIn&&visibility==='clients');const channels=[];if(settings.whatsapp_number&&show(settings.whatsapp_visibility))channels.push({kind:'whatsapp',label:'Chat on WhatsApp',address:settings.whatsapp_number,url:'https://wa.me/'+settings.whatsapp_number.slice(1)});if(settings.instagram_handle&&show(settings.instagram_visibility))channels.push({kind:'instagram',label:'Visit Instagram',address:'@'+settings.instagram_handle,url:'https://www.instagram.com/'+settings.instagram_handle+'/'});return {channels,response_note:channels.length?settings.response_note:''};}
export function saveContact(db:DatabaseSync,body:any,actor:string){
 if(!Number.isSafeInteger(body.version)||body.version<0)fail('Refresh the contact settings before saving.');
 const whatsapp=whatsappNumber(body.whatsapp_number),instagram=instagramHandle(body.instagram_handle),note=input(body.response_note,'Contact note',280);
 for(const channel of ['whatsapp','instagram'])if(!['hidden','clients','public'].includes(body[channel+'_visibility']))fail('Choose who can see each contact channel.');
 if(body.whatsapp_visibility!=='hidden'&&!whatsapp)fail('Add a WhatsApp number or hide this channel.');
 if(body.instagram_visibility!=='hidden'&&!instagram)fail('Add an Instagram profile or hide this channel.');
 return transaction(db,()=>{const result=db.prepare('UPDATE contact_settings SET whatsapp_number=?,whatsapp_visibility=?,instagram_handle=?,instagram_visibility=?,response_note=?,version=version+1,updated_at=datetime(\'now\') WHERE id=1 AND version=?').run(whatsapp,body.whatsapp_visibility,instagram,body.instagram_visibility,note,body.version);if(!result.changes)throw new ContactError('These settings changed in another tab. Copy your changes, reload, then save again.',409);db.prepare('INSERT INTO audit(id,actor_id,action,entity_id) VALUES(?,?,?,?)').run(id(),actor,'contact.settings','contact-settings');return contactSettings(db);});
}
