// Stable identifiers stored in library records and immutable published plan snapshots.
export const exerciseAnimationKeys = [
  'wall-push', 'push-up', 'floor-press',
  'row', 'band-row', 'reverse-fly',
  'shoulder-press', 'lateral-raise',
  'biceps-curl', 'hammer-curl',
  'triceps-extension', 'triceps-kickback',
  'dead-bug', 'bird-dog', 'plank',
  'glute-bridge', 'clamshell', 'standing-hip-abduction',
  'squat', 'reverse-lunge', 'hinge', 'romanian-deadlift',
  'calf-raise', 'seated-calf-raise',
  'incline-push-up', 'bench-press', 'lat-pulldown', 'front-raise',
  'concentration-curl', 'lying-triceps-extension', 'side-plank', 'mountain-climber',
  'bodyweight-squat', 'goblet-squat', 'split-squat', 'step-up', 'standing-leg-curl',
  'donkey-kick', 'sumo-squat', 'single-leg-calf-raise'
] as const;

// A separate content pack adds new examples without replacing earlier records.
// Copy is original and illustrative; Alex reviews the setup, load and range.
export const expandedStarterExercises = [
  ['starter-incline-push-up', 'Incline press-up', 'Chest', 'A stable raised surface that cannot slide', 'Place your hands on a secure raised surface and step your feet back. Keep your body in a steady line as you bend your elbows and bring your chest towards the surface, then press away. Choose the height and range with Alex.', 'incline-push-up'],
  ['starter-bench-press', 'Dumbbell bench press', 'Chest', 'Two dumbbells and a stable flat exercise bench', 'Lie on a stable bench with your head, shoulders and hips supported and feet firmly planted. Lower the dumbbells towards your chest with your wrists steady, then press up smoothly. Agree a manageable load and a suitable setup with Alex.', 'bench-press'],
  ['starter-lat-pulldown', 'Lat pulldown', 'Back', 'Lat pulldown machine', 'Adjust the seat and thigh pad so you are secure, with feet on the floor. Pull the bar down in front of you towards your upper chest, keeping your torso steady, then let it rise with control. Ask Alex to help set the grip and load.', 'lat-pulldown'],
  ['starter-front-raise', 'Single-arm dumbbell front raise', 'Shoulders', 'One light dumbbell', 'Stand tall with the weight beside your thigh and your elbow softly bent. Lift your arm forwards to a comfortable height, no higher than your shoulder, then lower slowly. Keep your body still without swinging, then repeat on the other side.', 'front-raise'],
  ['starter-concentration-curl', 'Dumbbell concentration curl', 'Biceps', 'One dumbbell and a stable seat', 'Sit with your feet apart and lean forwards slightly. Rest the back of your upper arm against your inner thigh, curl the weight towards your shoulder, then lower it steadily. Keep the upper arm in place and repeat on the other side.', 'concentration-curl'],
  ['starter-lying-triceps-extension', 'Lying dumbbell triceps extension', 'Triceps', 'Two light dumbbells and exercise mat', 'Lie on your back with knees bent and hold the dumbbells above your shoulders, palms facing each other. Keep your upper arms steady as you bend your elbows to lower the weights beside your head, then straighten your arms. Choose a comfortable range with Alex.', 'lying-triceps-extension'],
  ['starter-side-plank', 'Side plank', 'Core', 'Exercise mat', 'Lie on your side with your elbow beneath your shoulder and legs extended. Lift your hips into a steady line and breathe naturally. Hold for the time agreed with Alex, lower gently and repeat on the other side. Ask Alex about a knees-down variation if needed.', 'side-plank'],
  ['starter-mountain-climber', 'Slow mountain climber', 'Core', 'Exercise mat', 'Start with your hands beneath your shoulders and legs extended. Bring one knee towards your chest, return that foot, then change sides. Take it slowly and keep your hips steady; a smaller knee movement is a good place to start.', 'mountain-climber'],
  ['starter-bodyweight-squat', 'Bodyweight squat', 'Legs', 'No equipment', 'Stand with feet about shoulder-width apart and toes turned out slightly. Bend your hips and knees to lower within a comfortable range, then stand smoothly. Keep your feet grounded and let your knees follow the direction of your toes.', 'bodyweight-squat'],
  ['starter-goblet-squat', 'Dumbbell goblet squat', 'Legs', 'One dumbbell', 'Hold one dumbbell securely at your chest with both hands. Sit down between your hips within a comfortable range, keeping your feet grounded and knees moving with your toes, then stand smoothly. Choose the load and depth with Alex.', 'goblet-squat'],
  ['starter-split-squat', 'Split squat', 'Legs', 'No equipment; stable support if needed', 'Take a comfortable staggered stance with your rear heel lifted. Bend both knees to lower steadily, then press through your feet to rise without stepping. Keep your front foot grounded and repeat with the other leg in front. Use support if needed.', 'split-squat'],
  ['starter-step-up', 'Low step-up', 'Legs', 'A stable low exercise step; hand support if needed', 'Place one whole foot on a stable low step. Press through that foot to stand on the step, bringing your other foot alongside it, then step down slowly. Keep your knee moving in line with your toes and repeat with the other leading leg.', 'step-up'],
  ['starter-standing-leg-curl', 'Standing leg curl', 'Legs', 'A stable chair or support', 'Stand tall and hold a stable support. Bend one knee to lift your heel behind you, keeping your thighs alongside each other and hips steady. Lower the foot slowly and repeat on the other side. Use a comfortable range without swinging.', 'standing-leg-curl'],
  ['starter-donkey-kick', 'Donkey kick', 'Glutes', 'Exercise mat', 'Begin on hands and knees. Keep one knee bent as you lift that thigh behind you, stopping before your back arches or hips turn. Bring the knee back with control and repeat on the other side. A small, steady movement is enough to practise.', 'donkey-kick'],
  ['starter-sumo-squat', 'Dumbbell sumo squat', 'Glutes', 'One dumbbell', 'Stand with a comfortably wide stance and toes turned slightly out. Hold one dumbbell securely with both hands between your legs, bend your hips and knees, then stand with control. Keep your feet grounded and knees following your toes; choose the stance and load with Alex.', 'sumo-squat'],
  ['starter-single-leg-calf-raise', 'Supported single-leg calf raise', 'Calves', 'A stable chair or support', 'Hold a stable support and stand on one foot, with the other lifted clear of the floor. Raise your heel slowly, pause briefly, then lower with control. Keep your ankle steady and repeat on the other side. Alex can help choose a suitable variation.', 'single-leg-calf-raise']
] as const;

// Original example copy for Alex to review and tailor. Existing starter records
// remain in the first content pack so an upgrade never changes their cues.
export const additionalStarterExercises = [
  ['starter-push-up', 'Press-up', 'Chest', 'Exercise mat (optional)', 'Place your hands just wider than your shoulders and extend your legs. Keep your body in one line as you bend your elbows, then press the floor away. Take your time; Alex can help you choose a suitable variation.', 'push-up'],
  ['starter-floor-press', 'Dumbbell floor press', 'Chest', 'Two dumbbells and exercise mat', 'Lie on your back with knees bent and feet on the floor. Hold the dumbbells above your chest, lower until your upper arms gently meet the floor, then press up with control. Choose the load with Alex.', 'floor-press'],
  ['starter-band-row', 'Standing resistance band row', 'Back', 'Resistance band and secure chest-height anchor', 'Use a secure anchor and check the band before starting. Stand tall, draw your elbows back towards your sides, then return your hands slowly. Keep your shoulders relaxed and choose the tension with Alex.', 'band-row'],
  ['starter-reverse-fly', 'Dumbbell reverse fly', 'Back', 'Two light dumbbells', 'Soften your knees and hinge forwards with a steady back. With a slight bend in your elbows, open your arms out to the sides, then lower slowly. Keep the movement controlled and choose your range with Alex.', 'reverse-fly'],
  ['starter-shoulder-press', 'Dumbbell shoulder press', 'Shoulders', 'Two dumbbells', 'Stand tall with the dumbbells near shoulder height. Press them upwards within a comfortable range, then lower with control. Keep your ribs settled and choose the load with Alex.', 'shoulder-press'],
  ['starter-lateral-raise', 'Dumbbell lateral raise', 'Shoulders', 'Two light dumbbells', 'Stand tall with your arms by your sides and elbows softly bent. Raise your arms out to the sides to a comfortable height, no higher than your shoulders, then lower slowly. Keep your shoulders relaxed.', 'lateral-raise'],
  ['starter-biceps-curl', 'Dumbbell biceps curl', 'Biceps', 'Two dumbbells', 'Stand tall with palms facing forwards and upper arms near your sides. Bend your elbows to bring the weights towards your shoulders, then lower slowly. Let your arms do the work without swinging.', 'biceps-curl'],
  ['starter-hammer-curl', 'Dumbbell hammer curl', 'Biceps', 'Two dumbbells', 'Hold the dumbbells by your sides with palms facing inwards. Keep your upper arms steady as you bend your elbows, then lower with control. Choose a load that lets you move smoothly.', 'hammer-curl'],
  ['starter-triceps-extension', 'Overhead triceps extension', 'Triceps', 'One dumbbell', 'Hold one dumbbell securely with both hands above your head. Keep your upper arms steady as you bend your elbows to lower it behind your head, then straighten your arms. Choose a comfortable range and load with Alex.', 'triceps-extension'],
  ['starter-triceps-kickback', 'Supported triceps kickback', 'Triceps', 'One dumbbell and stable support', 'Support yourself securely and hinge forwards. Hold your upper arm alongside your torso, bend your elbow, then straighten it to move the dumbbell behind you. Return slowly without swinging your shoulder.', 'triceps-kickback'],
  ['starter-dead-bug', 'Dead bug', 'Core', 'Exercise mat', 'Lie on your back with arms up and knees bent above your hips. Slowly reach one arm and the opposite leg away while keeping your back steady. Return, then change sides. A smaller reach is a good place to start.', 'dead-bug'],
  ['starter-bird-dog', 'Bird dog', 'Core', 'Exercise mat', 'Start on hands and knees, with hands beneath shoulders and knees beneath hips. Reach one arm and the opposite leg away while keeping your hips level. Return with control and change sides; reach only as far as you can stay steady.', 'bird-dog'],
  ['starter-plank', 'Forearm plank', 'Core', 'Exercise mat', 'Place your elbows beneath your shoulders and extend your legs. Keep a steady line through your body while breathing naturally. Hold for the time agreed with Alex; you can ask Alex about a knees-down variation.', 'plank'],
  ['starter-glute-bridge', 'Glute bridge', 'Glutes', 'Exercise mat', 'Lie on your back with knees bent and feet flat on the floor. Press through your feet and lift your hips until your body forms a line from shoulders to knees. Lower slowly, keeping the movement comfortable.', 'glute-bridge'],
  ['starter-clamshell', 'Side-lying clamshell', 'Glutes', 'Exercise mat', 'Lie on your side with hips and knees bent and feet together. Keep your pelvis still as you open the top knee, then close it slowly. Work within a comfortable range and repeat on the other side.', 'clamshell'],
  ['starter-standing-hip-abduction', 'Standing side leg raise', 'Glutes', 'A stable chair or support', 'Stand tall and hold a stable support. Lift one leg out to the side without leaning your body, then lower it slowly. Keep your hips facing forwards and repeat on the other side.', 'standing-hip-abduction'],
  ['starter-reverse-lunge', 'Reverse lunge', 'Legs', 'No equipment; stable support if needed', 'Stand tall, take one foot back and bend both knees within a comfortable range. Press through the front foot to return to standing. Move steadily, use support if needed and repeat on the other side.', 'reverse-lunge'],
  ['starter-romanian-deadlift', 'Dumbbell Romanian deadlift', 'Legs', 'Two dumbbells', 'Stand with the dumbbells in front of your thighs and knees softly bent. Move your hips back, keeping the weights close to your legs and your back steady, then return to standing. Agree the load and range with Alex.', 'romanian-deadlift'],
  ['starter-calf-raise', 'Standing calf raise', 'Calves', 'A stable chair or support', 'Stand tall with a stable support to hand. Lift your heels slowly, pause briefly, then lower them with control. Keep the movement comfortable and take your time.', 'calf-raise'],
  ['starter-seated-calf-raise', 'Seated calf raise', 'Calves', 'A stable chair', 'Sit on a stable chair with feet flat on the floor and knees bent. Keep the balls of your feet down as you lift both heels, then lower slowly. Move through a comfortable range.', 'seated-calf-raise']
] as const;
