// Original short explanations, grounded in official adult guidance reviewed 2026-09-29.
// These support a conversation with Alex; they do not prescribe individual treatment.
const eatwell='https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/the-eatwell-guide/';
const movement='https://www.nhs.uk/live-well/exercise/physical-activity-guidelines-for-adults-aged-19-to-64/';
const strength='https://acsm.org/resistance-training-guidelines-update-2026/';
const chill='https://www.gov.uk/government/publications/how-to-chill-freeze-and-defrost-food-safely/how-to-chill-freeze-and-defrost-food-safely';
const cook='https://www.gov.uk/government/publications/cooking-your-food/cooking-your-food';
const rice='https://www.gov.uk/government/publications/home-food-fact-checker/home-food-fact-checker';
export const guides=[
 {id:'flavour',category:'Kitchen',title:'Keep flavour in the plan',summary:'Healthy eating can have plenty of flavour. Herbs, spices, garlic and lemon can help you rely less on added salt.',steps:['Read the recipe before cooking and set out what you need.','Taste a safely cooked portion before adding seasoning. Try a small change, then taste again.','Keep oils, sauces and toppings in your ingredient quantities. Alex can recalculate a personal recipe when you change it.'],action:'/portal/recipes',action_label:'Find something delicious',sources:[{name:'NHS salt and flavour guidance',url:'https://www.nhs.uk/live-well/eat-well/food-types/salt-in-your-diet/'}]},

 {id:'balance',category:'Food',title:'Build a plate you look forward to',summary:'Balance belongs across your day or week. Every meal does not need to be perfect.',steps:['Make room for fruit and vegetables, higher-fibre starchy foods and a protein food.','Include dairy or a suitable alternative, and small amounts of unsaturated oils.','Use variety and your preferences to keep food enjoyable.'],action:'/portal/recipes',action_label:'Find a meal',sources:[{name:'NHS Eatwell Guide',url:eatwell}]},
 {id:'fibre',category:'Food',title:'Give fibre a little attention',summary:'The UK adult guideline is 30g a day. It is a general reference, rather than an automatically assigned target.',steps:['Try oats, wholegrain bread, pulses, fruit and vegetables.','Check labels: fibre varies by product and preparation.','An unknown fibre estimate in the diary is missing information, not zero.'],action:'/portal/recipes?sort=fibre',action_label:'Explore fibre estimates',sources:[{name:'NHS fibre guidance',url:'https://www.nhs.uk/live-well/eat-well/digestive-health/how-to-get-more-fibre-into-your-diet/'}]},
 {id:'strength',category:'Training',title:'Simple can still be strong',summary:'Resistance training helps strength and muscle development. A routine you can keep doing matters.',steps:['Bands, bodyweight, machines and free weights can all be useful.','Follow your agreed programme and build difficulty gradually with Alex.','Compare the same exercise and reps. You do not have to train to failure for every set.'],action:'/portal/today',action_label:'Open your programme',sources:[{name:'ACSM 2026 resistance training update',url:strength}]},
 {id:'muscle',category:'Training',title:'Size and strength are different signals',summary:'Gaining scale weight does not tell you how much muscle you have gained.',steps:['Keep progressive resistance training at the centre of your muscle goal.','Review comparable loads and reps, optional measurements and how you feel.','Agree food portions and any targets with Alex; avoid guessing a large surplus from a goal label.'],action:'/portal/progress',action_label:'Review your progress',sources:[{name:'ACSM 2026 resistance training update',url:strength},{name:'NHS Eatwell Guide',url:eatwell}]},
 {id:'movement',category:'Training',title:'Movement comes in lots of forms',summary:'General adult guidance includes 150 minutes of moderate activity or 75 minutes of vigorous activity weekly, plus strengthening on at least two days.',steps:['Walking, dancing, cycling and adapted activities can all have a place.','Break up sitting where you can. Start gradually at a suitable intensity.','If you have medical concerns or have been inactive for some time, discuss starting with your GP.'],action:'/portal/progress?metric=cardio_minutes',action_label:'Note your activity',sources:[{name:'NHS adult activity guidance',url:movement}]},
 {id:'weight',category:'Goals',title:'See the week, not just the weigh-in',summary:'Eating habits, sleep, movement and personal circumstances all affect weight management.',steps:['Review trends with Alex, alongside energy and strength.','Use changes you can maintain. A difficult day does not erase your work.','Weight and measurements are optional. You can hide weight charts in your profile.'],action:'/portal/profile',action_label:'Make your goal yours',sources:[{name:'NHS weight management',url:'https://www.nhs.uk/better-health/lose-weight/'}]},
 {id:'hydration',category:'Recovery',title:'A small pause for a drink',summary:'6–8 cups or glasses daily is a general guide. Heat, activity and personal needs can change it.',steps:['Water is a useful choice; milk, tea and coffee can also count.','Drink through the day. Follow personal clinical advice if your fluid intake is restricted.'],action:'/portal/rhythm',action_label:'Choose your habits',sources:[{name:'NHS water and hydration',url:'https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/water-drinks-nutrition/'}]},
 {id:'sleep',category:'Recovery',title:'Give the evening a softer landing',summary:'A regular sleep routine and a calm wind-down can help you prepare for rest.',steps:['Try similar bed and wake times when possible.','Make space for reading, relaxing or writing tomorrow’s to-do list.','Notice what helps you. Persistent sleep difficulties deserve support from a health professional.'],action:'/portal/rhythm',action_label:'Make space for recovery',sources:[{name:'NHS Every Mind Matters',url:'https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/how-to-fall-asleep-faster-and-sleep-better/'}]},
 {id:'prep',category:'Kitchen',title:'Plan the week. Cook in manageable batches.',summary:'Choose meals first, check what is already in the kitchen, then shop for what is missing.',steps:['Read the method before starting. Weigh ingredients in the state specified: cooked, raw or drained.','Split leftovers into small containers, cool and refrigerate within 1–2 hours. Keep the fridge at 0–5°C.','Eat general leftovers within 48 hours or freeze sooner. Rice has stricter rules; open the rice guide.'],action:'/portal/planner',action_label:'Plan something delicious',sources:[{name:'FSA chilling and freezing',url:chill}]},
 {id:'rice',category:'Kitchen',title:'Rice needs a quicker cool-down',summary:'Rice storage needs extra care, even when a recipe uses already cooked rice.',steps:['Cool rice quickly, ideally within one hour, and refrigerate promptly.','Keep chilled rice for no more than 24 hours before eating or reheating.','Reheat only once, until steaming hot throughout. Take extra care with takeaway rice.'],action:'/portal/planner',action_label:'Back to your meals',sources:[{name:'FSA home food fact checker',url:rice}]},
 {id:'cooking',category:'Kitchen',title:'The timer is a helper, not a doneness test',summary:'Food, appliances and batch sizes need different cooking times. Follow the recipe and packaging.',steps:['Check that food is thoroughly cooked. A clean thermometer can check the centre reaches 70°C for two minutes or an equivalent combination.','For reheating, heat until steaming hot throughout and reheat only once.','Keep raw and ready-to-eat food apart. Wash hands and clean equipment; check labels and your dietary needs.'],action:'/portal/recipes',action_label:'Choose your recipe',sources:[{name:'FSA cooking guidance',url:cook}]}
];
