import type { DatabaseSync } from 'node:sqlite';
import { calculateRecipe } from './nutrition.ts';
const I=(code:string,grams:number)=>({food_id:'cofid-'+code,grams});
// Original editorial recipes. Alex can approve, tailor or archive them.
// Named cooked/drained ingredient weights must not be replaced with raw/dry weights.
export function installKitchenRecipes(db:DatabaseSync){
 const pack='kitchen-recipes-cofid-v2';if(db.prepare('SELECT id FROM content_packs WHERE id=?').get(pack))return;
 const recipes=[
  {title:'Lemon & garlic chicken couscous',yield:2,time:20,tags:['lunch','dinner','omnivore'],items:[I('18-323',240),I('11-902',320),I('13-523',160),I('13-517',200),I('14-277',20),I('13-244',6),I('17-038',10)],method:'Wash and chop the cucumber and tomatoes. Finely chop the garlic and mix with the measured lemon juice and olive oil. Use freshly cooked chicken and couscous in the cooked weights listed, or handle previously cooked portions according to storage instructions. Combine with the vegetables and dressing. Divide evenly into two servings. If serving warm, heat the cooked chicken and grain until steaming hot throughout before adding the vegetables.'},
  {title:'Ginger tofu & pea noodle pan',yield:2,time:25,tags:['dinner','vegetarian'],items:[I('13-570',320),I('11-941',320),I('13-536',160),I('13-505',160),I('13-890',10),I('13-244',6),I('17-038',10)],method:'Clean and slice the mushrooms; peel and finely chop the ginger and garlic. Heat the measured oil in a wide pan and cook the mushrooms until tender. Add ginger and garlic and stir briefly, without burning them. Add the steamed tofu, boiled peas and boiled egg noodles in the cooked weights listed, plus a splash of water. Stir until steaming hot throughout and divide into two servings. Egg noodles mean this recipe is vegetarian rather than plant-based.'},
  {title:'Creamy chickpea & spinach curry',yield:2,time:30,tags:['dinner','vegetarian'],items:[I('13-670',300),I('13-530',360),I('13-521',120),I('13-499',100),I('13-876',6),I('12-379',100),I('17-038',10),I('11-858',320)],method:'Wash the spinach and chop the onion. Soften the onion in the measured oil, then stir in the curry powder. Add the canned tomatoes and simmer until the onion is tender. Add the drained, heated chickpeas and spinach, stirring until the spinach wilts and the mixture is steaming hot. Take the pan off the heat and stir in the yoghurt. Divide between two plates with the listed weight of cooked basmati rice. Rice leftovers need rapid cooling and fridge storage of no more than 24 hours.'},
  {title:'Lentil & pepper tomato pot',yield:2,time:30,tags:['dinner','plant-based'],items:[I('13-661',320),I('13-318',160),I('13-530',360),I('13-499',100),I('13-244',6),I('17-038',10),I('11-981',120)],method:'Wash and dice the pepper; chop the onion and garlic. Soften onion and pepper in the measured oil. Add garlic, stir briefly, then add canned tomatoes and a splash of water. Simmer until the vegetables are tender. Stir in the boiled lentils in their cooked weight and heat until steaming hot throughout. Divide into two portions and serve each with half the listed bread.'},
  {title:'Lemon salmon & pea pasta',yield:2,time:20,tags:['dinner','fish','pasta'],items:[I('16-358',240),I('11-1129',320),I('13-536',160),I('14-277',20),I('17-038',10),I('13-844',10)],method:'Wash and chop the parsley. Use freshly steamed salmon, boiled pasta and boiled peas in the cooked weights listed. Gently combine the hot pasta and peas with measured olive oil and lemon juice. Flake in the cooked salmon, checking for bones, and add parsley. If using safely stored leftovers, heat until steaming hot throughout and reheat only once. Divide evenly into two servings.'},
  {title:'Tuna & kidney bean lemon salad',yield:1,time:15,tags:['lunch','fish'],items:[I('16-416',100),I('13-660',120),I('13-523',100),I('13-517',100),I('14-277',10),I('17-038',5),I('11-981',60)],method:'Prepare the canned kidney beans according to the pack, then cool promptly if serving cold. Wash and dice the cucumber and tomato. Drain the tuna and use the drained weights listed for tuna and beans. Combine with the measured lemon juice and olive oil. Serve with the wholemeal bread. Check tuna and bean packaging for storage instructions after opening.'},
  {title:'Egg & avocado breakfast toast',yield:1,time:15,tags:['breakfast','vegetarian'],items:[I('12-940',100),I('14-386',60),I('11-981',60),I('13-517',100),I('14-277',5)],method:'Use peeled, thoroughly boiled eggs in the cooked edible weight listed. Wash and slice the tomato. Mash the avocado flesh with the measured lemon juice. Toast the bread, spread with avocado and add sliced egg. Serve the tomato alongside. The avocado weight excludes skin and stone; the egg weight excludes shell.'},
  {title:'Jacket potato with lentil tomato filling',yield:2,time:25,tags:['lunch','dinner','plant-based'],items:[I('13-491',400),I('13-661',300),I('13-530',300),I('13-499',80),I('13-244',6),I('17-038',10)],method:'This time estimate starts with already baked potatoes. Use freshly baked potatoes in the cooked weight listed, including edible skin. Chop onion and garlic; soften the onion in the measured oil and add garlic briefly. Add canned tomatoes and simmer until the onion is tender. Stir in the cooked lentils and heat until steaming hot. Split the hot potatoes and divide the filling evenly between two servings. Follow packaging or your potato recipe if baking from raw; that takes extra time.'},
  {title:'Mushroom, spinach & garlic pasta',yield:2,time:25,tags:['dinner','plant-based','pasta'],items:[I('11-1129',320),I('13-505',240),I('13-521',120),I('13-244',8),I('17-038',10),I('14-277',10)],method:'Wash the spinach and clean and slice the mushrooms. Finely chop the garlic. Heat the measured oil in a wide pan and cook the mushrooms until tender. Add garlic and stir briefly without burning it, then add spinach and let it wilt. Fold in the boiled pasta in the cooked weight listed and a splash of water. Heat until steaming hot throughout, add measured lemon juice and divide into two servings.'},
  {title:'Lemon chickpea & parsley couscous',yield:2,time:20,tags:['lunch','plant-based'],items:[I('13-670',300),I('11-902',320),I('13-523',180),I('13-517',200),I('13-844',12),I('14-277',20),I('17-038',10)],method:'Use freshly prepared chickpeas and couscous in their cooked or drained weights listed. Wash and dice the cucumber and tomatoes, and chop the parsley. Combine measured lemon juice and olive oil, then toss with the vegetables, parsley, chickpeas and couscous. Divide evenly into two servings. For a cold meal, cool cooked ingredients promptly and keep refrigerated until serving.'},
  {title:'Banana & peanut overnight oat pot',yield:1,time:10,tags:['breakfast','vegetarian'],items:[I('11-788',50),I('12-313',150),I('14-318',100),I('14-892',15)],method:'Use the peeled banana weight listed. Mash half the banana and mix with the dry oats, milk and measured peanut butter. Cover and refrigerate overnight. Stir before serving and add the remaining sliced banana. Check the milk and peanut butter labels for your dietary requirements. This time estimate is preparation time and excludes overnight chilling.'},
  {title:'Warm chicken & tomato lunch wrap',yield:1,time:15,tags:['lunch','omnivore','wrap'],items:[I('18-323',120),I('11-925',60),I('13-517',100),I('13-521',40),I('12-379',40),I('14-277',5)],method:'Wash and slice the tomato and wash the spinach. Combine yoghurt with measured lemon juice. Use freshly grilled chicken in the cooked edible weight listed; if using safely stored cooked chicken, reheat only once until steaming hot throughout. Warm the tortilla briefly in a dry pan. Add chicken, tomato, spinach and the yoghurt dressing, then fold. Serve immediately.'}
 ];
 db.exec('BEGIN IMMEDIATE');try{recipes.forEach((r,n)=>{const c=calculateRecipe(r.items,r.yield);db.prepare('INSERT OR IGNORE INTO recipes(id,title,ingredients,portions,preparation,substitutions,ingredient_items,yield_servings,nutrition,tags,prep_minutes) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run('kitchen-v2-'+(n+1),r.title,c.items.map((i:any)=>`${i.grams}g · ${i.name}`).join('\n'),r.yield+' servings',r.method,'Alex can tailor ingredients, portions and flavours in a private client copy. Changes require recalculated nutrition; check labels and dietary needs.',JSON.stringify(c.items),r.yield,JSON.stringify(c.nutrition),JSON.stringify(r.tags),r.time);});db.prepare('INSERT INTO content_packs(id) VALUES(?)').run(pack);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}
}
